################################################################
# This configuration uses the same input format of GANimmator for generation
################################################################
outout_dir: './output/ganimator_format'

# for GANimator BVH data
repr: 'repr6d'
skeleton_name: 'mixamo'
use_velo: true
keep_y_pos: true
padding_last: true
requires_contact: true
joint_reduction: true
skeleton_aware: false
joints_group: null

# generate parameters
num_frames: '2x_nframes'
alpha: 0.01
num_steps: 3
noise_sigma: 10.0
coarse_ratio: '3x_patchsize'
# coarse_ratio: '0.1x_nframes'
pyr_factor: 0.75
num_stages_limit: -1
patch_size: 11
loop: false